packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@swc/core'
  - sharp
  - tree-sitter
  - tree-sitter-javascript
  - tree-sitter-python
  - tree-sitter-typescript
  - tree-sitter-vue
  - unrs-resolver
